name: Docker-GCP-CI-CD
on:
  push:
    tags:
      - '*'


env:
  PROJECT_ID: your-project-id
  REGION: us-central1
  REPONAME: ebook-engine
  SERVICE_NAME: your-service-name
  IMAGE_NAME: ebook-engine


jobs:
  docker-release:
    name: Build and Deploy FastAPI Container to Google App Engine
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')  # <-- Notice that I'm filtering here to only run when a tagged commit is pushed

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.SECRET_GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SECRET_GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
             ${{ env.REGION }}-docker.pkg.dev/${{ secrets.SECRET_GCP_PROJECT_ID }}/${{ env.REPONAME }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.outputs.short_ref }}
             ${{ env.REGION }}-docker.pkg.dev/${{ secrets.SECRET_GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
      # 從 GitHub Secrets 中提取敏感信息並替換 YAML 配置文件中的變數。
      - id: populate-configs
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          # SECRET_AUTH_URL: ${{ secrets.SECRET_AUTH_URL }}
          SECRET_DB_USER: ${{ secrets.SECRET_DB_USER }}
          SECRET_DB_PASS: ${{ secrets.SECRET_DB_PASS }}
          SECRET_DB_PORT: ${{ secrets.SECRET_DB_PORT }}
          SECRET_DB_NAME: ${{ secrets.SECRET_DB_NAME }}
          SECRET_DB_HOST: ${{ secrets.SECRET_DB_HOST }}
          # SECRET_INSTANCE_UNIX_SOCKET: ${{ secrets.SECRET_INSTANCE_UNIX_SOCKET }}
          # SECRET_CLOUD_SQL_INSTANCE: ${{ secrets.SECRET_CLOUD_SQL_INSTANCE }}
          # SECRET_SERVICE_API_KEY: ${{ secrets.SECRET_SERVICE_API_KEY }}
        with:
          app_yaml_path: ".github/configs/app.yaml"

      # 將處理後的 YAML 文件部署到 Google App Engine。
      - id: deploy
        name: Deploy Docker image to App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: '.github/configs/app.yaml'